### ISSUE TITLE
Updating support:appcompat-v7 or support:design to 23.1.1 crashes

### ISSUE THREAD

**Issue by leomarques** [rey5137/material#292]
Updating support:appcompat-v7 or support:design to the latest version (23.1.1) causes crashes, latest working is 23.1.0.

Updating support:appcompat-v7 causes a crash at app start:
java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenuPresenter

Updating support:design causes a crash when I try to use a component from the library:
java.lang.VerifyError: com/rey/material/app/SimpleDialog

**Comment by aumidbek** [comment]
+

**Comment by jaydeep17** [comment]
+1
Same here
Upgrading creates proguard errors

**Comment by dnutcracker** [comment]
Same here

**Comment by Kane-Shih** [comment]
+1

**Comment by pinetree-kr** [comment]
+1

**Comment by luminousman** [comment]
+1
same here

**Comment by getintouchapp** [comment]
Likewise. Got this error :  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.internal.widget.TintTypedArray" on path: DexPathList

**Comment by MedoElkamaly** [comment]
+1

**Comment by beydogan** [comment]
+1

**Comment by pavanjaju** [comment]
+1
I got this java.lang.NoClassDefFoundError: com.rey.material.widget.YearPicker

**Comment by Kane-Shih** [comment]
W/dalvikvm(25426): VFY: unable to resolve new-instance 6182 (Lcom/rey/material/app/SimpleDialog$InternalListView;) in Lcom/rey/material/app/SimpleDialog;
W/dalvikvm(25426): VFY: Ljava/lang/Object; is not instance of Landroid/view/View;
W/dalvikvm(25426): VFY: bad arg 1 (into Landroid/view/View;)
W/dalvikvm(25426): VFY:  rejecting call to Lcom/rey/material/app/Dialog;.contentView (Landroid/view/View;)Lcom/rey/material/app/Dialog;
W/dalvikvm(25426): VFY:  rejecting opcode 0x6f at 0x0017
W/dalvikvm(25426): Verifier rejected class Lcom/rey/material/app/SimpleDialog;
D/AndroidRuntime(25426): Shutting down VM
E/AndroidRuntime(25426): FATAL EXCEPTION: main
E/AndroidRuntime(25426): java.lang.VerifyError: com/rey/material/app/SimpleDialog
E/AndroidRuntime(25426): 	at com.rey.material.app.SimpleDialog$Builder.onBuild

**Comment by harri35** [comment]
+1

**Comment by evgenii-kanivets** [comment]
+1

**Comment by manjunathc23** [comment]
+1

**Comment by getintouchapp** [comment]
I have fixed the errors and forked it here: https://github.com/getintouchapp/material_fork

If you guys want it clone the repo and build the jar to include it manually in your library

**Comment by getintouchapp** [comment]
The fixed errors and GUI with new compatibility library : https://play.google.com/store/apps/details?id=co.getintouch.play That's my production app

**Comment by jjhesk** [comment]
++++1

**Comment by kkroid** [comment]
+10086

**Comment by Kane-Shih** [comment]
@getintouchapp Does the fork project contain your new commit?

**Comment by kkroid** [comment]
@pavanjaju I got the same problem:"NoClassDefFoundError: com.rey.material.widget.YearPicker"

**Comment by ttpho** [comment]
+1
java.lang.NoClassDefFoundError: com.rey.material.widget.YearPicker

**Comment by fernandodev** [comment]
+1
Because 
`android.support.v7.internal.widget.TintTypedArray` now is `import android.support.v7.widget.TintTypedArray;`

Packages are moved from `internal` to `v7.widget`

I'm working on a PR did someone else fix it?
@getintouchapp your repo doesn't include changes you have listed. Have you done their?

**Comment by fernandodev** [comment]
@leomarques , @Kane-Shih I've done a PR that fix this issue: #299 
May you @rey5137 review my #299 PR and include those changes to a new SNAPSHOT version?

Thanks all

**Comment by kkroid** [comment]
After import the source code to local, and change all "android.support.v7.internal.widget*" to "android.support.v7.widget.*" it works. 
And you may also need add some attrs in attrs.xml file, for example:"<attr name="android:gravity"/>
        <attr name="prompt" format="reference" />
        <attr name="disableChildrenWhenDisabled" format="boolean" />"

**Comment by fernandodev** [comment]
@kkroid exactly ;)

**Comment by leomarques** [comment]
@fernandodev Thank you very much, I'll still wait a few months until the end of my project to see if @rey5137 will put it into the project so I don't have to download anything else for now.

**Comment by Prographer** [comment]
+1

I downgraded to 23.1.0

**Comment by rey5137** [comment]
I have released 1.2.2 version that fixed this bug.

**Comment by Prographer** [comment]
@rey5137 Thank you!

**Comment by afjcjsbx** [comment]
I have the same problem with 1.2.2 version.
My stack:
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.afjcjsbx.pronosticionline1x2, PID: 20564
                                                                                  java.lang.VerifyError: com/rey/material/widget/Spinner
                                                                                      at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:775)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:778)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:512)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:409)
                                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:358)
                                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                                      at com.afjcjsbx.pronosticionline1x2.Schedina.onCreate(Schedina.java:79)
                                                                                      at android.app.Activity.performCreate(Activity.java:5302)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2313)
                                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:141)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1238)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:136)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:681)
                                                                                      at dalvik.system.NativeStart.main(Native Method)

**Comment by yeganehaym** [comment]
+1

**Comment by wznshuai** [comment]
+10086

**Comment by hasid** [comment]
Use dependensies

compile 'com.github.rey5137:material:1.2.1'

and sync project

**Comment by krisha23** [comment]
After upgrading to 1.2.2 this error did not get resolved.

Infact, I started getting errors in all snackbars that used com.rey.material.widget.SnackBar.

No solution yet.

**Comment by noorzaie** [comment]
+2

**Comment by blackDiamonds38** [comment]
Caused by: java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenuPresenter 
I got this error .. is there any solution to such Error.?? What should I do to resolve it.? This thread is also seems to have specific solution on the problem... ;(

**Comment by VivekChodvadiya** [comment]
+2
same here

Anyone found solution??
